/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "auth": {
            "password_mismatched": string;
            "have_to_respond": string;
        };
        "bid": {
            "file_must_exists": string;
            "not_found": string;
            "error": string;
        };
        "editor": {
            "not_created": string;
            "not_found": string;
        };
        "file": {
            "not_found": string;
            "not_exist": string;
            "file_upload": string;
        };
        "folder": {
            "not_found": string;
            "not_exist": string;
        };
        "playlist": {
            "not_found": string;
        };
        "invoice": {
            "minimum_sum": string;
            "not_found": string;
            "file": string;
        };
        "monitor": {
            "not_created": string;
            "not_found": string;
        };
        "user": {
            "email": string;
            "password": string;
            "role": string;
            "exists": string;
            "not_created": string;
            "not_exist": string;
        };
        "demoTimeIsUp": string;
        "FORBIDDEN": string;
        "CONFLICT": string;
        "BAD_REQUEST": string;
        "SERVER_ERROR": string;
        "NOT_ACCEPTABLE": string;
        "NOT_FOUND": string;
        "NOT_IMPLEMENTED": string;
        "PRECONDITION": string;
        "SERVICE_UNAVAILABLE": string;
        "UNAUTHORIZED": string;
        "BALANCE": string;
        "LIMITED_STORE_SPACE": string;
        "DENIED_ADVERTISER": string;
        "CONFLICT_ERROR": string;
    };
    "validation": {
        "IS_DEFINED": string;
        "IS_EMPTY": string;
        "IS_DEFINED_REFRESH": string;
        "IS_PHONE_NUMBER": string;
        "IS_NOT_EMPTY": string;
        "IS_UUID": string;
        "IS_NUMBER": string;
        "IS_INT": string;
        "IS_ENUM": string;
        "IS_STRING": string;
        "IS_DATE": string;
        "IS_DATE_RANGE": string;
        "IS_EMAIL": string;
        "IS_BOOLEAN": string;
        "IS_URL": string;
        "IS_JSON": string;
        "IS_POSITIVE": string;
        "IS_OPTIONAL": string;
        "PASSWORD_MIN_LENGTH": string;
        "PASSWORD_MAX_LENGTH": string;
        "PASSWORD_TOO_WEAK": string;
        "MATCHES": string;
        "VALIDATE_NESTED": string;
        "MIN": string;
        "MIN_LENGTH": string;
        "MAX": string;
        "LENGTH": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
