/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "demoTimeIsUp": string;
        "FORBIDDEN": string;
        "CONFLICT": string;
        "BAD_REQUEST": string;
        "SERVER_ERROR": string;
        "NOT_ACCEPTABLE": string;
        "NOT_FOUND": string;
        "NOT_IMPLEMENTED": string;
        "PRECONDITION": string;
        "SERVICE_UNAVAILABLE": string;
        "UNAUTHORIZED": string;
        "PASSWORD_MISMATCHED": string;
        "YOU_HAVE_TO_RESPOND": string;
        "BALANCE": string;
        "LIMITED_STORE_SPACE": string;
        "DENIED_ADVERTISER": string;
        "USER_EMAIL": string;
        "USER_PASSWORD": string;
        "USER_ROLE": string;
        "USER_EXISTS": string;
        "USER_NOT_EXISTS": string;
        "BID_FILE_MUST_EXISTS": string;
        "FOLDER_NOT_EXIST": string;
        "FILE_NOT_EXIST": string;
        "CONFLICT_ERROR": string;
        "PLAYLIST_NOT_FOUND": string;
        "BID_NOT_FOUND": string;
        "BID_ERROR": string;
        "INVOICE_FILE": string;
        "EDITOR_NOT_FOUND": string;
    };
    "validation": {
        "IS_DEFINED": string;
        "IS_EMPTY": string;
        "IS_DEFINED_REFRESH": string;
        "IS_PHONE_NUMBER": string;
        "IS_NOT_EMPTY": string;
        "IS_UUID": string;
        "IS_NUMBER": string;
        "IS_INT": string;
        "IS_ENUM": string;
        "IS_STRING": string;
        "IS_DATE": string;
        "IS_DATE_RANGE": string;
        "IS_EMAIL": string;
        "IS_BOOLEAN": string;
        "IS_URL": string;
        "IS_JSON": string;
        "IS_POSITIVE": string;
        "IS_OPTIONAL": string;
        "PASSWORD_MIN_LENGTH": string;
        "PASSWORD_MAX_LENGTH": string;
        "PASSWORD_TOO_WEAK": string;
        "MATCHES": string;
        "VALIDATE_NESTED": string;
        "MIN": string;
        "MIN_LENGTH": string;
        "MAX": string;
        "LENGTH": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
