# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-test-install-deploy:
    docker:
      # specify the version you desire here
      - image: cimg/node:18.17.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project/myscreen/api-backend

    steps:
      - checkout
      - run: echo "Hello world !"

workflows:
  build-test-install-deploy-test:
    jobs:
      - build-test-install-deploy
