export enum Controllers {
  AUTH = 'AUTH',
  ACT = 'ACT',
  APPLICATION = 'APPLICATION',
  EDITOR = 'EDITOR',
  FILE = 'FILE',
  FOLDER = 'FOLDER',
  INVOICE = 'INVOICE',
  MONITOR = 'MONITOR',
  PLAYLIST = 'PLAYLIST',
  OTHER = 'OTHER',
}
