export enum MonitorCategoryEnum {
  GAS_STATION = 'GAS_STATION',
  MALL = 'MALL',
  COMMERCIAL_CENTRE = 'COMMERCIAL_CENTRE',
  MUNICIPAL_INSTITUTION = 'MUNICIPAL_INSTITUTION',
  EDUCATIONAL_INSTITUTION = 'EDUCATIONAL_INSTITUTION',
  RETAIL_SHOP = 'RETAIL_SHOP',
  STREET_MONITOR = 'STREET_MONITOR',
  SHOWCASE = 'SHOWCASE',
  STELLA = 'STELLA',
}
