version: '3.2'

networks:
  default:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local

services:
  rabbitmq:
    image: bitnami/rabbitmq:3.12.14
    restart: always
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_PASSWORD=MAnMCMrP7q
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=50Mb
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
    ports:
      - "5672:5672"
      - "15672:15672"
