version: '3.2'

networks:
  default:
    driver: bridge

volumes:
  postgres:
  pgadmin4:
  rabbitmq_data:
    driver: local

services:
  postgres:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: myscreen
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4:8.2
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 8088
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "QweAsdZxc321"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
      PGADMIN_CONFIG_CHECK_SUPPORTED_BROWSER: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 6
      PGADMIN_CONFIG_LANGUAGES: '{''ru'': ''Russian''}'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./postgresql-root.crt:/var/lib/pgadmin/postgresql-root.crt
      - ./id_rsa:/var/lib/pgadmin/id_rsa
      - ./pgpassfile:/pgadmin4/pgpassfile
      - pgadmin4:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres:postgres"
    ports:
      - "${PGADMIN_PORT:-8088}:8088"

  rabbitmq:
    image: bitnami/rabbitmq:3.12.13
    restart: always
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_PASSWORD=MAnMCMrP7q
      - RABBITMQ_USERNAME=admin
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
    ports:
      - "5672:5672"
      - "15672:15672"
